### ISSUE TITLE
What is the latest release of this fork?

### ISSUE THREAD

**Issue by rusefi** [miho/freerouting#14]
here on github I see 1.4.0 release

https://freerouting.mihosoft.eu/ says "download 1.3.0"?

**Comment by Ingrimmel** [comment]
The latest release of this fork is indeed 1.4.0. 
@miho has simply not yet released the software on this website.

**Comment by miho** [comment]
The latest release is now 1.4.1 which includes self-contained apps for Linux, macOS and Windows. The webpage has been updated.
