### ISSUE TITLE
Version number on Windows installation

### ISSUE THREAD

**Issue by andrasfuchs** [miho/freerouting#20]
I have just installed the freerouting-SNAPSHOT-2020-03-20_19-07-19-windows-x64.msi on Windows 10.

When I open the Apps & features Freerouting displays the version number of 0.0.0.

![image](https://user-images.githubusercontent.com/910321/77229466-7a52db80-6b8e-11ea-87bc-7a59b497a308.png)

**Comment by miho** [comment]
This is correct for the snapshot version. Release versions will show the correct version number. This version number forces potential testers to uninstall any previously installed version prior to testing the snapshot one.

**Comment by andrasfuchs** [comment]
Good to know, thanks!
