### ISSUE TITLE
Windows installation directory

### ISSUE THREAD

**Issue by andrasfuchs** [miho/freerouting#21]
I tested the freerouting-SNAPSHOT-2020-03-20_19-07-19-windows-x64.msi Windows installer.

There is no option to choose the installation directory, and the MSI installer installs Freerouting.exe into the C:\Users\<username>\AppData\Local\Freerouting\ directory.

The normal "Program Files" would be more ideal.

**Comment by miho** [comment]
Actually, AppData is the default for user installs without admin rights. We use the Windows defaults for app installs. In many companies this is important for users without admin rights. If you want to create an additional installer for system-wide installation then just add another build job that creates an installer with admin rights. Let me know if you need help with that.

**Comment by andrasfuchs** [comment]
Alright, that's fine, I don't mind.
