### ISSUE TITLE
Decouple the GUI from the router algorithm

### ISSUE THREAD

**Issue by andrasfuchs** [miho/freerouting#8]
The source code wasn't design in a way that helps further development too much. 

One of the major show stoppers is that the GUI and the router logic is so connected that it makes it impossible to:
* Create multi-threaded operations, and faster parallel computations
* Use more flexibility with scripting
* Use the auto-router as a background service/web API to an EDA

One way to decouple these two is to implement the Model-View-Controller design pattern and use events on the router logic class(es) and let the GUI subscribe to those events. 
It is substantial work, but it might worth it in the long run.

**Comment by andrasfuchs** [comment]
I run the [IntelliJ IDEA's Inspect Code](https://www.jetbrains.com/help/idea/running-inspections.html) feature today on the whole project, and it has many (good) warnings/suggestions:
![image](https://user-images.githubusercontent.com/910321/75629797-54689580-5be5-11ea-9c2b-d3259e94c136.png)

**Comment by miho** [comment]
archived
