### ISSUE TITLE
stop_pass_no not initialized

### ISSUE THREAD

**Issue by fjonsson** [miho/freerouting#9]
Just downloaded this version of freerouting to give it a try. Great to see some activity in the project!

I tried building and running the project within Eclipse, but when I try to start the routing it immediately stops. After some digging I found that the variable stop_pass_no is 0. Perhaps this is since I don't run from the command line and use the -mp option. If setting a default value (in the AutorouteSettings constructor) the routing works.

**Comment by andrasfuchs** [comment]
Thank you for the feedback @fjonsson and the diagnosis. I'll look into it in the next few days.

**Comment by andrasfuchs** [comment]
@fjonsson It should be fixed now.
